# Generated by Django 4.1.3 on 2022-12-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='FormData',
        ),
    ]
